version: 1

build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/ansible-runner:stable-2.16-latest

dependencies:
  python: requirements.txt
  system: bindep.txt
  galaxy: requirements.yml

additional_build_files:
  - src: files/
    dest: files/

options:
  package_manager_path: /usr/bin/microdnf

ansible_config: files/ansible.cfg
